# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'waterLevelDetector' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'


  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]


 pod 'RSKImageCropper'
 pod 'QBImagePickerController'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'


  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end

pod 'React', path: '../node_modules/react-native', subspecs: [
     'ART',
]
